name: "MDXLD Build Action"
description: "Build and bundle MDXLD files into ES Modules"
author: "MDXLD Team"

inputs:
  source:
    description: "Source directory containing MDX files"
    required: false
    default: "content"
  output:
    description: "Output directory for processed files"
    required: false
    default: ".mdx"
  config:
    description: "Path to config file"
    required: false
  bundle:
    description: "Bundle with esbuild"
    required: false
    default: "true"
  node-version:
    description: "Node.js version to use"
    required: false
    default: "20.x"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        
    - name: Install dependencies
      shell: bash
      run: npm install -g mdxld

    - name: Build MDXLD files
      shell: bash
      run: |
        BUNDLE_ARG=""
        if [ "${{ inputs.bundle }}" == "true" ]; then
          BUNDLE_ARG="--bundle"
        fi
        
        CONFIG_ARG=""
        if [ -n "${{ inputs.config }}" ]; then
          CONFIG_ARG="--config ${{ inputs.config }}"
        fi
        
        mdxld build --source ${{ inputs.source }} --output ${{ inputs.output }} $CONFIG_ARG $BUNDLE_ARG
