name: Build MDXLD Files with Custom Config

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build MDXLD files
        uses: mdxld/action@v1
        with:
          source: "src/content"
          output: "dist/mdx"
          config: ".mdxld.config.js"
